AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ga-fedex-test  # This is the name of your existing Lambda function
      Handler: lambda_function.lambda_handler  # Update this to point to your handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::926456375548:role/ShivLambdaRole
      Description: A simple hello world Lambda function



# AWSTemplateFormatVersion: '2010-09-09'
# Transform: AWS::Serverless-2016-10-31

# Resources:
#   HelloWorldFunction:
#     Type: AWS::Serverless::Function
#     Properties:
#       FunctionName: gh-action
#       Handler: hello_world.app.lambda_handler
#       Runtime: python3.9
#       CodeUri: hello_world/
#       MemorySize: 128
#       Timeout: 5
#       Description: A simple hello world Lambda function
