AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: .
      FunctionName: gh-action  # Specify your Lambda function name here
      MemorySize: 128
      Timeout: 60
      Policies: 
        - AWSLambdaBasicExecutionRole
