name: Deploy Lambda Function

on:
  push:
    branches:
      - main # or any other branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Build SAM Application
      run: |
        sam build
      working-directory: src/ # Directory where your template.yaml is located

    - name: Package SAM Application
      run: |
        sam package --s3-bucket samvedortest --output-template-file packaged.yaml --region us-east-1
      working-directory: src/

    - name: Deploy SAM Application
      run: |
        sam deploy --template-file packaged.yaml --stack-name github-vendor2 --capabilities CAPABILITY_IAM --region us-east-1
      working-directory: src/
