name: Deploy Lambda Function with SAM

on:
  push:
    paths:
      - "src/**"  # Watch changes in the src/ directory
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Replace with your AWS region
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install aws-sam-cli

      - name: Build and package Lambda function with SAM
        run: |
          cd src
          sam build
          sam package --s3-bucket your-s3-bucket --output-template-file packaged.yaml
      
      - name: Deploy Lambda function with SAM
        run: |
          sam deploy --template-file packaged.yaml --stack-name your-stack-name --capabilities CAPABILITY_IAM
