name: Update Lambda Function with SAM

on:
  push:
    paths:
      - "src/**"
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SAM CLI
        run: |
          curl -sS https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -o aws-sam-cli.zip
          unzip aws-sam-cli.zip
          sudo ./aws-sam-cli/install
      - name: Build SAM application
        run: sam build
      - name: Update SAM application
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"
        run: sam package --template-file template.yaml --s3-bucket gh-action-us-east-2 --output-template-file updated-template.yaml && sam deploy --template-file updated-template.yaml --stack-name gh-action --capabilities CAPABILITY_IAM