name: Deploy Lambda Function

on:
  push:
    paths:
       - "src/**"
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - name: Install dependencies
       run: sudo apt-get update && sudo apt-get install -y python3-pip
     - name: Install AWS SAM CLI
       run: pip3 install aws-sam-cli
     - name: Build SAM application
       run: cd src && sam build --use-container
     - name: Deploy SAM application
       run: |
         cd src
         sam deploy --no-confirm-changeset --stack-name my-stack --capabilities CAPABILITY_IAM
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: "us-east-2"
